"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { collection, getDocs } from "firebase/firestore";
import { auth } from "@/lib/firebase/auth";
import { db } from "@/lib/firebase/client-app";

const initial = { enabled: false, startDate: "", endDate: "", targetDays: "15", restaurantName: "", restaurantRef: "", restaurantImage: "", title: "", description: "", prizeTitle: "", prizeValue: "", prizeDescription: "", imageUrl: "" };
const defaultDescription = (days: string, restaurant: string) => `Jouez sur Proxiplay pendant au moins ${days || "15"} jours differents pendant la periode du jeu pour tenter de gagner un repas pour 2 chez ${restaurant || "le restaurant du mois"}. Une seule journee est comptabilisee par jour. Les joueurs ayant atteint l'objectif participent automatiquement au tirage au sort organise a la fin du jeu.`;

export default function RestaurantMonthlyChallengePage() {
  const [form, setForm] = useState(initial); const [error, setError] = useState<string | null>(null); const [saved, setSaved] = useState(false);
  const [restaurants, setRestaurants] = useState<Array<{ id: string; name: string; image: string }>>([]);
  const descriptionCustomized = useRef(false);
  useEffect(() => { let active = true; void (async () => { try { const user = auth.currentUser; if (!user) return; const response = await fetch("/api/admin/monthly-challenge?type=restaurant", { headers: { Authorization: `Bearer ${await user.getIdToken()}` } }); const payload = await response.json() as { config?: Record<string, unknown> | null }; const config = payload.config; if (!active || !config) return; const date = (value: unknown) => { const timestamp = value as { seconds?: number; _seconds?: number } | null; const seconds = timestamp?.seconds ?? timestamp?._seconds; return typeof seconds === "number" ? new Date(seconds * 1000).toISOString().slice(0, 10) : ""; }; const description = String(config.description ?? "").trim(); descriptionCustomized.current = Boolean(description); setForm((current) => ({ ...current, enabled: config.enabled === true, startDate: date(config.start_date), endDate: date(config.end_date), targetDays: String(config.target_days ?? current.targetDays), restaurantRef: String(config.restaurant_ref ?? ""), restaurantName: String(config.restaurant_name ?? ""), restaurantImage: String(config.restaurant_image ?? ""), title: String(config.title ?? ""), description: description || defaultDescription(String(config.target_days ?? current.targetDays), String(config.restaurant_name ?? "")), prizeTitle: String(config.prize_title ?? ""), prizeDescription: String(config.prize_description ?? ""), prizeValue: String(config.prize_value ?? ""), imageUrl: String(config.image_url ?? "") })); } catch { if (active) setError("Impossible de charger le Resto du mois."); } })(); return () => { active = false; }; }, []);
  useEffect(() => { void getDocs(collection(db, "enseignes")).then((snap) => setRestaurants(snap.docs.map((doc) => { const data = doc.data(); return { id: doc.id, name: String(data.name ?? data.nom ?? data.title ?? doc.id), image: String(data.image_url ?? data.logo ?? data.photo ?? "") }; }).sort((left, right) => left.name.localeCompare(right.name, "fr")))).catch(() => setError("Impossible de charger les enseignes.")); }, []);
  const update = (key: keyof typeof initial, value: string | boolean) => {
    if (key === "description") descriptionCustomized.current = true;
    setForm((current) => ({ ...current, [key]: value, ...(!descriptionCustomized.current && key === "targetDays" ? { description: defaultDescription(String(value), current.restaurantName) } : {}) }));
  };
  async function save() {
    setError(null); setSaved(false); const user = auth.currentUser; if (!user) return setError("Connexion admin requise.");
    const start = new Date(`${form.startDate}T00:00`); const end = new Date(`${form.endDate}T00:00`);
    const response = await fetch("/api/admin/monthly-challenge", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${await user.getIdToken()}` }, body: JSON.stringify({ type: "restaurant", enabled: form.enabled, start_date: { seconds: Math.floor(start.getTime() / 1000), nanoseconds: 0 }, end_date: { seconds: Math.floor(end.getTime() / 1000), nanoseconds: 0 }, target_days: Number(form.targetDays), restaurant_name: form.restaurantName, restaurant_ref: form.restaurantRef, restaurant_image: form.restaurantImage, title: form.title, description: form.description, prize_title: form.prizeTitle, prize_value: Number(form.prizeValue) || 0, prize_description: form.prizeDescription, image_url: form.imageUrl }) });
    if (!response.ok) { const body = await response.json().catch(() => null) as { error?: string } | null; return setError(body?.error || "Impossible d'enregistrer le Resto du mois."); } setSaved(true);
  }
  const field = (label: string, key: keyof typeof initial, type = "text") => <label className="flex flex-col gap-1.5"><span className="text-[12px] font-medium text-[#666]">{label}</span><input className="rounded-[8px] border border-[#E0E0DA] px-3 py-2 text-[14px]" type={type} value={String(form[key])} onChange={(event) => update(key, event.target.value)} /></label>;
  return <section className="min-h-full bg-[#F7F7F5]"><div className="mx-auto grid max-w-[900px] gap-6"><div className="flex justify-between"><div><h1 className="text-[22px] font-medium">Resto du mois</h1><p className="mt-1 text-[14px] text-[#666]">Configurez la campagne restaurant et son tirage automatique.</p></div><Link href="/admin/games" className="rounded-[10px] border px-5 py-3 text-[14px]">Retour aux jeux</Link></div><form className="rounded-[12px] border bg-white p-5" onSubmit={(event) => { event.preventDefault(); void save(); }}><label className="mb-4 flex gap-2 text-[13px]"><input type="checkbox" checked={form.enabled} onChange={(event) => update("enabled", event.target.checked)} />Defi actif</label><div className="grid gap-4 sm:grid-cols-2">{field("Date de debut", "startDate", "date")}{field("Date de fin", "endDate", "date")}{field("Objectif en jours actifs", "targetDays", "number")}<label className="flex flex-col gap-1.5"><span className="text-[12px] font-medium text-[#666]">Restaurant partenaire</span><select className="rounded-[8px] border px-3 py-2" value={form.restaurantRef} onChange={(event) => { const restaurant = restaurants.find((item) => item.id === event.target.value); setForm((current) => ({ ...current, restaurantRef: restaurant ? `enseignes/${restaurant.id}` : "", restaurantName: restaurant?.name ?? "", restaurantImage: restaurant?.image ?? "" })); }}><option value="">Choisir une enseigne</option>{restaurants.map((restaurant) => <option key={restaurant.id} value={restaurant.id}>{restaurant.name}</option>)}</select></label>{field("Titre", "title")}{field("Lot", "prizeTitle")}{field("Valeur du lot", "prizeValue", "number")}{field("Detail du lot", "prizeDescription")}{field("Image", "imageUrl")}</div><label className="mt-4 flex flex-col gap-1.5"><span className="text-[12px] font-medium text-[#666]">Reglement / explication du jeu</span><textarea className="min-h-28 rounded-[8px] border px-3 py-2 text-[14px]" value={form.description} onChange={(event) => update("description", event.target.value)} /></label>{error ? <p className="mt-4 text-[#E24B4A]">{error}</p> : null}{saved ? <p className="mt-4 text-[#3B6D11]">Resto du mois enregistre.</p> : null}<button className="mt-5 rounded-[10px] bg-[#639922] px-5 py-3 text-white">Enregistrer</button></form></div></section>;
}
